import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import OptionsColumn from "./ui/global/OptionsColumn";
import UsersColumn from "./ui/global/UsersColumn";
import MidColumn from "./ui/global/MidColumn";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + 'h-screen bg-neutral-50 flex justify-center'}>
        <div className="flex w-4/6 bg-gray-10">
          <OptionsColumn />
          <MidColumn>
            {children}
          </MidColumn>
          <UsersColumn />
        </div>
      </body>
    </html>
  );
}