import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LeftColumn from "./ui/global/ColumnLeft";
import RightColumn from "./ui/global/ColumnRight";
import MidColumn from "./ui/global/ColumnMid";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + 'h-screen bg-neutral-50 flex justify-center dark:bg-neutral-800'}>
        <div className="flex w-4/6">
          <LeftColumn />
          <MidColumn>
            {children}
          </MidColumn>
          <RightColumn />
        </div>
      </body>
    </html>
  );
}